# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [prereleased, created]

jobs:

  build:
    strategy:
      matrix:
        os: ["windows", "linux", "darwin"]
        arch: ["amd64", "arm64"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o wow-profile-copy-${{ matrix.os }}-${{ matrix.arch }} -v .
    
    - name: Store Binary in Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}-${{ matrix.arch }}
        path: wow-profile-copy-${{ matrix.os }}-${{ matrix.arch }}
    
  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: build
          pattern: build-*
          delete-merged: true

  release:
    runs-on: ubunu-latest
    needs: merge
    permissions:
      contents: write
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifacts@v4

      - name: Attach Binaries
        run: gh release upload ${{ github.ref_name }} ./build/*
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  
